"""empty message

Revision ID: 0da036f4451f
Revises: e79eccc5ceb7
Create Date: 2023-08-13 00:09:09.318783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da036f4451f'
down_revision = 'e79eccc5ceb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('existing_plant_existing_plant', schema=None) as batch_op:
        batch_op.alter_column('nbrOfhouseholds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('powerForProductiveUsed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('existing_plant_existing_plant', schema=None) as batch_op:
        batch_op.alter_column('powerForProductiveUsed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('nbrOfhouseholds',
               existing_type=sa.INTEGER(),
               nullable=False)

    #op.create_table('spatial_ref_sys',
    #sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    #sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    #sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    #)
    # ### end Alembic commands ###
