"""empty message

Revision ID: 275382cd42e0
Revises: 98f182a2541b
Create Date: 2023-08-05 18:58:22.761726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275382cd42e0'
down_revision = '98f182a2541b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory_demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dem_ter', sa.Float(), nullable=False))
        batch_op.drop_column('demTer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory_demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demTer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('dem_ter')

    # ### end Alembic commands ###
