"""empty message

Revision ID: 44bac9d93e66
Revises: 9714c979e051
Create Date: 2023-06-29 19:20:57.067229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bac9d93e66'
down_revision = '9714c979e051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inserttable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inserttable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machineid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stateid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statechange', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unixtime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extras', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='inserttable_pkey')
    )
    # ### end Alembic commands ###
