"""empty message

Revision ID: 584f3f5d47bf
Revises: f0b777c1d742
Create Date: 2023-06-29 20:26:37.739861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584f3f5d47bf'
down_revision = 'f0b777c1d742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provinces')
    # ### end Alembic commands ###
