"""empty message

Revision ID: 90565eb6eb49
Revises: e38cf2aa04c3
Create Date: 2023-08-13 11:24:16.184664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90565eb6eb49'
down_revision = 'e38cf2aa04c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('projects_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataRadius', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_index('idx_projects_project_geomCentroid_0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_project', schema=None) as batch_op:
        batch_op.create_index('idx_projects_project_geomCentroid_0', ['geomCentroid'], unique=False)
        batch_op.drop_column('dataRadius')

    """op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )"""
    # ### end Alembic commands ###
