"""empty message

Revision ID: 92f315230f96
Revises: bdc34ec849c5
Create Date: 2023-06-29 20:22:24.025433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f315230f96'
down_revision = 'bdc34ec849c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provinces')
    # ### end Alembic commands ###
