"""empty message

Revision ID: 98f182a2541b
Revises: cd1a7fbb0b1e
Create Date: 2023-08-05 18:52:28.432719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f182a2541b'
down_revision = 'cd1a7fbb0b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territory_demand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('men', sa.Float(), nullable=False),
    sa.Column('dem', sa.Float(), nullable=False),
    sa.Column('demTer', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('territory_demand')
    # ### end Alembic commands ###
