"""empty message

Revision ID: e38cf2aa04c3
Revises: 0da036f4451f
Create Date: 2023-08-13 08:10:36.913151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'e38cf2aa04c3'
down_revision = '0da036f4451f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_project_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wording', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wording', sa.String(length=80), nullable=False),
    sa.Column('plannedPowerForHouseholds', sa.Float(), nullable=False),
    sa.Column('plannedPowerForProductive', sa.Float(), nullable=False),
    sa.Column('nbrHouseholds', sa.Integer(), nullable=False),
    sa.Column('geomCentroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['projects_project_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects_project', schema=None) as batch_op:
        batch_op.create_index('idx_projects_project_geomCentroid_0', ['geomCentroid'], unique=False, postgresql_using='gist')

    #op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )"""
    with op.batch_alter_table('projects_project', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_project_geomCentroid_0', postgresql_using='gist')

    op.drop_table('projects_project')
    op.drop_table('projects_project_type')
    # ### end Alembic commands ###
